### ISSUE TITLE
[Bug] SMB Grunt Instability

### ISSUE THREAD

**Issue by rasta-mouse** [cobbr/Covenant#154] opened 2020-03-14 18:39 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Not really sure how to quantify this one.  SMB Grunts seem to randomly go into a Lost status when they're issued a Task.  The process is still running on the remote target, and the `Connect` command doesn't move it back into an `Active` status.

**To Reproduce**
1. Generate an SMB Grunt Binary Launcher
2. Upload the Launcher to a remote target
3. Execute the Launcher (via `WMIGruntCommand` or similar)
4. SMB Grunt stages as expected
5. Issue a Task
6. SMB Grunt goes into a `Lost` status

**Expected behavior**
Task should return output.
`Connect` should reconnect to the SMB Grunt?

**Screenshots**
![image](https://user-images.githubusercontent.com/7346521/76688212-b8964b00-6622-11ea-92e1-251f347e989e.png)
![image](https://user-images.githubusercontent.com/7346521/76688206-b03e1000-6622-11ea-8f14-9ad56b7a5cda.png)
![image](https://user-images.githubusercontent.com/7346521/76688228-db286400-6622-11ea-820c-11b16785673e.png)

**Covenant Server Information:**
 - OS: Kali Linux 2020.1
 - Docker or Native: Native

**Browser Information:**
 - Browser: Chrome
 - Version: 80.0.3987.132 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows Server 2016 Standard
 - Version:  1607, Build 14393.3542

**Comment by RythmStick** [comment] 2020-03-14 19:07
I've also seen the exactly the same issues running Covenant on Windows 10/Native.

**Comment by rasta-mouse** [comment] 2020-03-14 21:00
I've also just noticed that the task status will stay as `tasked`, but actually returns results when you issue another Task.

Before:
![image](https://user-images.githubusercontent.com/7346521/76690312-a920fd00-6636-11ea-8097-3dcff35f20c6.png)

After:
![image](https://user-images.githubusercontent.com/7346521/76690319-bfc75400-6636-11ea-8c60-9147f7bc6563.png)

and `pwd` won't return until I issue another Task.

**Comment by 3lpsy** [comment] 2020-03-15 21:36
This has happened to me several times. It's most common when I try to do something with networking elements like pivoting but it has also happened when using the Assembly task as well.

**Comment by mofer** [comment] 2020-05-03 23:39
I have exactly the same situation that RastaMouse.

**Comment by cobbr** [comment] 2020-09-19 20:31
I believe this should now be fixed in master. Closing for now. If issues persist, just let me know and we can re-open.

**Closed by cobbr** 2020-09-19 20:31 UTC

**Comment by joncave** [comment] 2020-10-07 20:03
This is still an issue. It's easier to reproduce if you set the delay on your SMB Grunt to 0.

The root cause is a deadlock that occurs when an incoming message is processed by TaskExecute in a thread and takes longer to write output than the sleep time on the main loop. If the main loop gets around to call `messenger.ReadTaskingMessage()` again then it will lock `_UpstreamLock` until data is read from the pipe. When the task has data to return it will call `WriteTaskingMessage()` which will block because it cannot obtain the `_UpstreamLock` lock. The situation 'resolves' if another tasks is sent because the read operation will complete and allow the previous response write to be processed.

Steps to reproduce:

1. Connect to an SMB Grunt will a low delay (i.e. 0)
2. Issue a slower running task or one that uses OutputStream (e.g. `Rubeus triage`)

The task will sit at "tasked" with no output being shown. Issuing another command will unlock it and output returned.

I was able to fix this for testing by simply removing the `lock (_UpstreamLock)` references and it seemed to work okay. However, I'm not sure if this will cause other problems.
