### ISSUE TITLE
[Bug] Cannot create listener

### ISSUE THREAD

**Issue by L34Rn** [cobbr/Covenant#169] opened 2020-05-16 19:47 UTC
**Bug**

```
First run, but cannot create listener.
```

**Steps to reproduce the behavior:**
```
1- Follow install instructions here
2- Click on 'Listeners' in the left-hand sidebar
3- Click on 'Create' on the Listeners page
4- See error
```

**Expected behavior**
```
To create a listener.
```

**Error:**
```
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Covenant.Views.Listener.Views_Listener__CreateBridgeListener+<>c__DisplayClass20_0+<<ExecuteAsync>b__2>d.MoveNext() in _CreateBridgeListener.cshtml, line 44
```
```
NullReferenceException: Object reference not set to an instance of an object.
Covenant.Views.Listener.Views_Listener__CreateBridgeListener+<>c__DisplayClass20_0+<<ExecuteAsync>b__2>d.MoveNext() in _CreateBridgeListener.cshtml
+
            <input asp-for="ConnectAddresses[0]" value="@Model.ConnectAddresses[0]" class="form-control address">
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(bool useCachedResult, HtmlEncoder encoder)
Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
Covenant.Views.Listener.Views_Listener__CreateBridgeListener.ExecuteAsync() in _CreateBridgeListener.cshtml
+
    ListenerType lt = ListenerTypes.FirstOrDefault(LT => LT.Name == "Bridge");
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(string partialViewName, object model, ViewDataDictionary viewData, TextWriter writer)
Covenant.Views.Listener.Views_Listener_Create.ExecuteAsync() in Create.cshtml
+
            await Html.RenderPartialAsync("_CreateBridgeListener", new BridgeListener());
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync<TFilter, TFilterAsync>()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Covenant Server Information:**
```
Ubuntu 5.4.0-6ubuntu1~16.04.4
x64
```

**Comment by L34Rn** [comment] 2020-05-16 19:55
dotnet core sdk version `2.2.100`

**Comment by layderv** [comment] 2020-05-19 13:21
Can you post the settings you used to create the listener please?

**Comment by emmasuki** [comment] 2020-05-29 15:50
seems related/duplicate of this: https://github.com/cobbr/Covenant/issues/115

**Comment by cobbr** [comment] 2020-05-30 14:49
Closing as duplicate, will address this in #115

**Closed by cobbr** 2020-05-30 14:49 UTC
Labels: duplicate
