### ISSUE TITLE
[Bug] Multiple connect addresses are specified, but only one is being used.

### ISSUE THREAD

**Issue by zeroformsec** [cobbr/Covenant#126] opened 2019-12-16 22:35 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
When defining multiple Connect Addresses for the Listener only one gets saved in the listener configuration.

**To Reproduce**
1. Add a new Listener.
2. Specify multiple ConnectAddress fields.
3. Create the listener.
4. Select the newly created listener, only one IP address is visible.

**Expected behavior**
There should be multiple connect addresses present in the listener properties, as well as in the launcher code.

**Screenshots**
IP addresses are removed from the screenshots.

![c2](https://user-images.githubusercontent.com/58169987/70948758-37540a00-206d-11ea-85b4-9410038d6040.png)

![2](https://user-images.githubusercontent.com/58169987/70948776-420e9f00-206d-11ea-8474-c9aac0f14726.png)

**Covenant Server Information:**
 - OS: Ubuntu LTS 18.04
 - Docker or Native: Native

**Browser Information:**
 - Browser Firefox
 - Version 71.0 64 bit.

**Target Information (System that implant is running on):**
 - OS: Windows 10 64 bit.

**Additional context**
N/A.

**Comment by rasta-mouse** [comment] 2019-12-16 22:36
Duplicate of #122 ?

**Comment by zeroformsec** [comment] 2019-12-16 22:42
Seems like it, sorry I didn't see the existing issues, I just went and reported it.

**Comment by cobbr** [comment] 2020-01-25 14:45
Closing as duplicate.

**Closed by cobbr** 2020-01-25 14:45 UTC
Labels: duplicate
