### ISSUE TITLE
[Bug] "HttpPostRequest" Not Updated on Listener Profile Changes.

### ISSUE THREAD

**Issue by Iorpim** [cobbr/Covenant#207] opened 2020-07-14 00:27 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
When creating/editing HTTP Listener profiles, the "HttpPostRequest" property of the HttpProfiles variable is not updated, causing ParseExact(/Core/Utilities.cs:185) to fail, throwing an exception and returning 500.

**To Reproduce**
1. Go to Listeners --> Profiles --> CustomHttpProfile(Or create a new one).
2. Locate the HttpPostRequest text box.
3. Replace any character. (E.g. "i=a19ea(…)" --> "i=a29ea(…)")
4. Start Listener with edited profile.
5. Generate, and run Launcher.

**Expected behavior**
The profile changes should be reflected on the listener, returning a full grunt session upon execution.

**Screenshots**
![image](https://user-images.githubusercontent.com/22481687/87366322-c9ae8480-c54e-11ea-8a8f-247f08f20f9d.png)

**Covenant Server Information:**
 - OS: Ubuntu 18.04.1 (AWS)
 - Docker or Native: Docker

**Additional context**
For debugging, I edited the HTTPListenerController file, printing the received post data, and the expected post template, and I noticed the template did not change regardless of the listener profile selected, always returning the default "i=a19ea23062db990386a3a478cb89d52e&data={DATA}&session=75db-99b1-25fe4e9afbe58696-320bea73".

**Comment by cobbr** [comment] 2020-07-15 18:30
@Iorpim Are you trying to edit an HttpProfile applied to a previously created Listener?

**Comment by Iorpim** [comment] 2020-07-15 18:40
@cobbr I will admit I did during my debugging process, however, I did just try to create a new listener, to be sure that wasn't the problem, and I got the same error.
Thanks for the reminder.

**Comment by cobbr** [comment] 2020-07-15 18:42
Okay thanks, I'll see if I can reproduce.

**Comment by cobbr** [comment] 2020-07-15 20:29
Confirmed, looks like there's a bug editing profiles. I'll work on a fix. In the meantime, it looks like rebooting the Covenant server fixes the issue.

**Comment by Iorpim** [comment] 2020-07-15 20:34
That's nice to know, thank you very much!

**Comment by cobbr** [comment] 2020-08-26 04:19
I think I fixed this a while ago, and forgot to update this issue. Closing for now, this should be fixed.

If you continue to have issues with the latest code, we can reopen the issue.

**Closed by cobbr** 2020-08-26 04:19 UTC
Labels: bug
