### ISSUE TITLE
[Bug] BridgeListener ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by merlin123h** [cobbr/Covenant#203] opened 2020-07-07 06:01 UTC
Hi every body.
At first, i have one question.
Can we install covenant on the Ubuntu 20.04 (focal) server?
I asked this question, because i have installed covenant on Ubuntu server. After installing, i can not create listener. note that, my dot net version is: Dot net SDK 3.0.1.
Please guide me about why i can't create listener? 
Also, tell me about my first question.

Thanks.

**Comment by d-sec-net** [comment] 2020-07-07 07:49
Are you running as root?

**Comment by merlin123h** [comment] 2020-07-07 08:42
Well,
i have tested it as root and non root user. both of them came with same result, error.

**Comment by fhlip0** [comment] 2020-07-07 09:29
@merlin123h  what error are you receiving?

**Comment by merlin123h** [comment] 2020-07-07 10:57
this is error.
![Screenshot_2020-07-07 Internal Server Error](https://user-images.githubusercontent.com/67941449/86770702-fe02dc00-c048-11ea-9ec2-814a638bdd8e.png)

**Comment by cobbr** [comment] 2020-07-07 15:36
@merlin123h I think I know what the issue is here. This is going to be an issue specific to BridgeListeners. Are you intending to use a BridgeLister? An HttpListener should not have this issue.

**Comment by merlin123h** [comment] 2020-07-08 10:32
No. 
I don't reach to the part to select listener type. After login to my panel in covenant C2, i would like to create listener. As soon as i click to create button at listener section, this error (attached picture
![Screenshot_2020-07-07 Internal Server Error](https://user-images.githubusercontent.com/67941449/86908602-b5155b00-c10e-11ea-9035-80361ffb32e6.png)
) occurs.

Please guide me how to create listener at covenant's first using.

Thanks.

**Comment by cobbr** [comment] 2020-07-08 22:23
Ahh I see, this triggers when navigating to the Create page. I think this should now be fixed in the `dev` branch. Would you mind trying out the dev branch to see if that fixes your issue @merlin123h ?

**Comment by cobbr** [comment] 2020-07-24 21:47
Closing for now, feel free to let me know and we can re-open if the issues persists.

**Closed by cobbr** 2020-07-24 21:47 UTC
Labels: bug, question
