### ISSUE TITLE
Bug - Grunt is not updating it's killdate from the datepicker.

### ISSUE THREAD

**Issue by jfmaes** [cobbr/Covenant#304] opened 2021-03-23 14:35 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**

The datepicker for grunt generation is not injecting the correct killdate back into the actual grunt.

**To Reproduce**
1. Go to 'Launchers (after creating an appropriate listener)'
2. Click on 'Binary.'
3. Scroll down to 'killdate'
4. Select a killdate using the datepicker
5. generate and download the grunt
6. execute the grunt
7. check the grunts information in the grunts tab
8. the killdate will not match your selected date, but will be reset to the original killdate value, this issue only occurs using the datepicker, it does not occurs when you manually enter a date.

**Expected behavior**

the grunt should have its killdate injected corresponding with the date from the datepicker.

**Covenant Server Information:**
 - OS: linux
 - native

**Browser Information:**
 -  both in chrome and firefox

**Target Information (System that implant is running on):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by jfmaes** [comment] 2021-03-29 10:18
to add on that, seems like the default date value is not taking datetime.now into account but the datetime during installation. resulting in killdates of the past if you did not reinstall covenant for a while

**Comment by aancw** [comment] 2021-04-23 08:53
![image](https://user-images.githubusercontent.com/6284204/115846276-ee277d80-a44b-11eb-8bc5-e688b30e1306.png)

Confirmed it reset to default

![image](https://user-images.githubusercontent.com/6284204/115846358-04cdd480-a44c-11eb-9223-3439b9e7b6fe.png)

**Comment by cobbr** [comment] 2021-05-01 20:49
It turns out the bootstrap-datetimepicker doesn't trigger the onchange event when selecting via the UI.

Had to do some frustrating javascript interop to fix this, but it's fixed in the dev branch. If you are still on master, you can work around this by typing a date into the input field manually.

**Closed by cobbr** 2021-05-01 20:49 UTC
Labels: bug
