### ISSUE TITLE
[Bug] Changing admin certificate breaks Grunt communication

### ISSUE THREAD

**Issue by s3nn** [cobbr/Covenant#143] opened 2020-02-20 16:05 UTC
**Bug Description**
When attempting to change Covenant's `admin` certificate by following what was mentioned in #102 , Covenant throws out the following exception:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLTM3DFPH7QR", Request id "0HLTM3DFPH7QR:00000002": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /root/tools/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /root/tools/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /root/tools/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /root/tools/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)
2020-02-20 15:41:39.1726|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLTM3DFPH7QR", Request id "0HLTM3DFPH7QR:00000002": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /root/tools/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /root/tools/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /root/tools/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /root/tools/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application
```

**To Reproduce**
1. Obtain a valid SSL certificate signed by a CA (e.g. Let' s Encrypt)
`cd /etc/letsencrypt/archive/domain`
`openssl pkcs12 -export -out domain.pfx -inkey privkey1.pem -in cert.pem -certfile chain.pem`
`openssl x509 -pubkey -outform der -in cert.pem -out domain.cer`
`mv domain.pfx /root/tools/Covenant/Covenant/Data/covenant-dev-private.pfx`
`mv domain.cer /root/tools/Covenant/Covenant/Data/covenant-dev-public.cer`
`cd /root/toos/Covenant/Covenant/`
`dotnet build`
`dotnet run`
2. Visit Covenant `admin` UI at https://domain:7443 without getting errors
3. Execute any Launcher and try to establish a connection with a Grunt; this will fail, even if the Listener uses plain HTTP.

**Expected behavior**
1. Use a valid SSL certificate signed by a CA for Covenant's `admin` UI
2. Execute any Launcher and establish a connection with a Grunt

**Covenant Server Information:**
 - OS: Kali Linux on AWS
 - Native
- Launchers used: Binary, PowerShell, MSBuild

**Additional context**
- Certificate obtained via Let's Encrypt and it works perfectly when I visit the `admin` UI using Chromium or Firefox

**The following is weird**
What I find weird about this is that when I am using the self-signed Covenant certificate, all Grunt connections work just fine (either over plain HTTP, using SSL and / or enabling ValidateCert and CertPinning). 

I then stop Covenant, I replace the certificates using the commands above, build and run Covenant, and the admin UI is not throwing any SSL errors (as expected) but the same Launchers that worked 1-2 mins ago cause Covenant to throw the exception included above, including Launchers that connect to plain HTTP Listeners.

I have tried the following:
- Removed the covenant.db file before replacing the certificates and building again
- Created new Listeners before and after replacing the certs
- Ran wireshark and saw that the Grunt communicates with Covenant but gets back the following:
`The remote server returned an error: (500) Internal Server Error.`

I'd be grateful if you could point me in the right direction about what is causing this issue.

p.s thanks for the great tool

Sincerely,
s3nn

**Comment by fasetto** [comment] 2020-03-19 20:09
I have same issue. I got ssl from Let's Encrypt. And used that certificate. 
Created a new grunt but when I run grunt on lab computer it closes immediately. 
I saw these logs on command line.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUC83AQOUOQ", Request id "0HLUC83AQOUOQ:00000002": An unhandled exception was thrown
by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /home/fasetto/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /home/fasetto/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-03-19 20:05:30.6833|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLUC83AQOUOQ", Request id "0HLUC83AQOUOQ:00000002": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /home/fasetto/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /home/fasetto/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUC83AQOUP2", Request id "0HLUC83AQOUP2:00000002": An unhandled exception was thrown
by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /home/fasetto/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /home/fasetto/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
e, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& stat                                                                                                             at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2020-03-19 20:06:12.0928|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HLUC83AQOUP2", Request id "0HLUC83AQOUP2:00000002": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Covenant.API.CovenantAPIExtensions.ApiGruntsGuidByGuidGetAsync(ICovenantAPI operations, String guid, CancellationToken cancellationToken) in /home/fasetto/Covenant/Covenant/API/CovenantAPIExtensions.cs:line 1267
   at Covenant.Models.Listeners.InternalListener.GetGruntForGuid(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 287
   at Covenant.Models.Listeners.InternalListener.Read(String guid) in /home/fasetto/Covenant/Covenant/Models/Listeners/InternalListener.cs:line 321
   at Covenant.Controllers.HttpListenerController.Post() in /home/fasetto/Covenant/Covenant/Controllers/ListenerControllers/HttpListenerController.cs:line 72
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
sultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionRe                                                                                                             at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by mepher** [comment] 2020-07-28 13:36
Try this: update to support TLS 1.2 `(SecurityProtocolType)3072`

Line 61 in the Grunt Template StagerCode :
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls;
`
Line 608 in the Grunt Template ExecutorCode
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls;
`

**Comment by s3nn** [comment] 2020-08-05 10:02
@mepher thanks, but can you explain (if you know) why changing the cert for the admin interface changes the cert used by grunts?

**Comment by cobbr** [comment] 2021-02-11 21:32
Apologies for the very late response @s3nn @fasetto.

I'm not able to reproduce this issue, I'm thinking there must be an issue with the certificate you have created, but I'm not sure what.

Here's the instructions I used to generate a new certificate:

```
openssl req -x509 -days 365 -newkey rsa:2048 -keyout key.pem -out cert.pem
openssl pkcs12 -export -out covenant-dev-private.pfx -inkey key.pem -in cert.pem
openssl x509 -pubkey -outform der -in cert.pem -out covenant-dev-public.cer
```

Make sure you do not use a password to protect the private PFX, Covenant is not expecting one.

**Comment by fasetto** [comment] 2021-02-11 23:05
I was trying to use generated certificate from the Lets Encrypt. That is causing the error if I remember correctly.
I did setup nginx with reverse proxy instead, that solved my issue.

**Comment by cobbr** [comment] 2021-02-12 23:32
Hmm not sure why that would be necessary @fasetto .

Going to close this for now, since I am unable to reproduce. If anyone is still running into this issue, just let me know and we can re-open.

**Closed by cobbr** 2021-02-12 23:32 UTC
Labels: cant-reproduce, question
