### ISSUE TITLE
[Bug] HTA files error with "Binary stream '0' does not contain a valid BinaryHeader"

### ISSUE THREAD

**Issue by sandwich-destroyer** [cobbr/Covenant#136] opened 2020-01-24 15:44 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
HTAs are not launching successfully

**To Reproduce**
1. Create HTA launcher
2. Host file
3. Browse to file with IE
4. Click allow
5. Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53576838/73081850-30df5c00-3e7d-11ea-8e95-240e20358bd4.png)

**Covenant Server Information:**
 - OS: Windows 10 Enterprise 1903
 - Docker or Native: Docker

**Browser Information:**
 - Browser Internet Explorer

**Target Information (System that implant is running on):**
 - OS: Windows 10 Enterprise 1903

**Additional context**

**Comment by sandwich-destroyer** [comment] 2020-01-25 22:55
Resolution in #135

**Comment by sandwich-destroyer** [comment] 2020-01-25 23:09
Issue still exists

**Comment by cobbr** [comment] 2020-01-26 04:30
Closing as a duplicate of #28 

Let me know if you think this is not the same issue, and we can re-open.

**Closed by cobbr** 2020-01-26 04:30 UTC
Labels: duplicate
