### ISSUE TITLE
[Bug] Exception setting ConnectAddresses on Listener

### ISSUE THREAD

**Issue by Mursi-Alzanati** [cobbr/Covenant#168] opened 2020-05-04 21:01 UTC
Bug

Covenant crash for no clear reason, even after I wiping the database  with ( rm Data\covenant.db ) it work for a while then crash again ( usually create listener >> launcher >>  after few minutes covenant go off) 

**To Reproduce**
1. Follow install instructions [here](https://github.com/cobbr/Covenant/wiki/Installation-And-Startup#option-1---dotnet-core)
2. Click on 'Listeners' in the left-hand sidebar
3. Click on 'Create' on the Listeners page
4. Click on 'Launcher' in the left-hand sidebar
5. Click on PowerShell
6. Create Launcher like [here ](https://github.com/cobbr/Covenant/wiki/Launchers)
7. Work fine for less than 2 hours then crash
8. wiping database ( rm Data\covenant.db )
9. repeat from 1- 8

![image](https://user-images.githubusercontent.com/64800151/81012854-efd6ea80-8e62-11ea-97da-93fcaf5a3f8a.png)

**Covenant Server Information:**
 - OS: kali 2020
 - Native

**Browser Information:**
 - Chrome
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Target Information (System that implant is running on):**
 - OS: Windows 10
 - Version 1809

**Comment by rasta-mouse** [comment] 2020-05-04 21:08
Is this a duplicate of #167?

**Comment by Mursi-Alzanati** [comment] 2020-05-04 21:15
I am not sure, but after I delete the database covenant works fine then i experience the issue in #167 and sometimes it just work fine then crashed without experiencing #167

**Comment by 3lpsy** [comment] 2020-05-04 21:49
You would need to post the config for your listener (i.e what connect addresses are you using)

**Comment by Mursi-Alzanati** [comment] 2020-05-06 13:12
All default except the IP Address: 10.8.0.xxx port 80

**Comment by cobbr** [comment] 2020-05-30 14:43
Closing as duplicate. Will address this in #167

**Closed by cobbr** 2020-05-30 14:43 UTC
Labels: duplicate
