### ISSUE TITLE
[Bug] Importing a template fails

### ISSUE THREAD

**Issue by py7hagoras** [cobbr/Covenant#294] opened 2021-03-05 18:58 UTC
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
Attempts to import an exported template fails.

**To Reproduce**
Export any Template and try to import it.

**Expected behavior**
Template should import without any errors just like for Tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/6564346/110160998-be001e80-7dba-11eb-9d66-4d6aed9b6ede.png)

**Covenant Server Information:**
 - OS - Kali 2020.3
 - Native

**Browser Information:**
 - Chrome

**Comment by cobbr** [comment] 2021-03-05 19:16
@py7hagoras It looks like there's an issue with the YAML format you are using to import. How did you create the template YAML? Are you able to share the YAML text?

My guess is you are not using a YAML List, which is required for Import.

**Comment by py7hagoras** [comment] 2021-03-05 19:35
It was just a modified GruntHTTP template that I tried to import from another Covenant server. I also exported a default template eg GruntSMB and tried to re-import it to same server, but I got same error.

**Comment by cobbr** [comment] 2021-03-05 20:04
@py7hagoras Are you confident that you are using the latest commits to the dev branch? Are your two Covenant servers even at the same commit?

I'm unable to reproduce this, and I'm pretty confident in the level of testing I've done on template importing/exporting. But there has definitely been some adjustments over the last few weeks.

**Comment by py7hagoras** [comment] 2021-03-05 20:59
Yes, I cloned dev like 3 hours ago. I just checked for Tasks and its also the same error, cant import Tasks, tried on both chrome and IE.

[PrivateTemplate.txt](https://github.com/cobbr/Covenant/files/6093341/PrivateTemplate.txt)

**Comment by cobbr** [comment] 2021-03-05 21:16
@py7hagoras Yeah, as I suspected this template is not properly using a YAML list. Is it possible you generated this YAML file with an older version of Covenant? I would try re-generated the template YAML with the current dev branch.

**Comment by py7hagoras** [comment] 2021-03-05 22:21
@cobbr I have exported the default GruntSMB template from the latest dev, and tried to re-import it and got the same error. I have attached the exported GruntSMB template. I'm able to manually create a task or template, but exporting and re-importing doesn't seem to work for me.
[ExportedGruntSMBTemplateFromLatestDev.txt](https://github.com/cobbr/Covenant/files/6093714/ExportedGruntSMBTemplateFromLatestDev.txt)

**Comment by cobbr** [comment] 2021-03-05 22:26
Very weird. I think I have an idea what might be happening. There's a few different ways to export at this point, maybe I've missed patching one of them up. Are you using the Action bar to Export, the Export All button, or clicking Export from the edit page?

**Comment by py7hagoras** [comment] 2021-03-05 22:30
So I just tried from the Action bar, from the ImplantTemplates page and from the Edit page - they were all the same, couldn't re-import them

**Comment by cobbr** [comment] 2021-03-05 22:53
Can you run `git log` and grab the latest commit hash you are on?

**Comment by cobbr** [comment] 2021-03-05 22:56
Ok, so I am able to reproduce this, but only if I Export from the Edit page. I'm guessing that must be what's happening.

**Comment by py7hagoras** [comment] 2021-03-05 23:28
@cobbr Does this mean custom tasks generated from a previous Covenant version will have to be manually created for this latest version? or is there any other way around it?

**Comment by cobbr** [comment] 2021-03-06 00:05
I'm not sure, let me follow up, it may have always accepted a List. Either way it's pretty easy to convert it to a List.

**Comment by cobbr** [comment] 2021-05-01 20:59
I believe this issue has been fixed in dev.

**Closed by cobbr** 2021-05-01 20:59 UTC
