### ISSUE TITLE
[Issue] BypassUACGrunt "Parameter count mismatch"

### ISSUE THREAD

**Issue by avi8892** [cobbr/Covenant#38] opened 2019-08-20 07:20 UTC
When trying to run tasks on Grunts, Getting powershell errors.

**Local OS** : Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux
**.NET version -**  .NET Core 2.2
**Target OS -**  Windows 10 Build 1803
Browser version - Firefox Version 60.8.0esr (64-bit)

![image](https://user-images.githubusercontent.com/31028818/63326076-23ed9800-c334-11e9-88bb-3b8ac4bb53d3.png)

**Comment by cobbr** [comment] 2019-08-20 15:57
Hey @avi8892, this does not look like a PowerShell error to me.

It's possible that this has something to do with using Kali. Can you try using docker or another host OS just to verify if that is the problem?

**Comment by avi8892** [comment] 2019-08-20 19:06
Sure, I will try on another OS hopefully it will work.

בתאריך 20 באוג׳ 2019 18:57,‏ Ryan Cobb <notifications@github.com> כתב:

Hey @avi8892<https://github.com/avi8892>, this does not look like a PowerShell error to me.

It's possible that this has something to do with using Kali. Can you try using docker or another host OS just to verify if that is the problem?

**Comment by cobbr** [comment] 2019-08-21 20:13
I've verified that Covenant works on Kali, so that's not the issue. Is .NET 4.8 installed on the target system?

**Comment by cobbr** [comment] 2019-08-21 22:02
I think you might be running into an AMSI issue. Can you try to disable Defender and see if the issue persists?

You just need to set the following by using gpedit:

Local Computer Policy -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Defender Antivirus -> Turn off Windows Defender Antivirus: Enabled
Local Computer Policy -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Defender Antivirus -> Real-time Protection -> Turn off real-time protection: Enabled

**Comment by avi8892** [comment] 2019-08-22 04:49
Hi Rayn, I have maked sure that Windows defender is turned off. I don't think it is AMSI protection. If for some reason, bypaccuac is working on your system, close this issue. I will try to solve it somehow.

בתאריך 22 באוג׳ 2019 01:02,‏ Ryan Cobb <notifications@github.com> כתב:

I think you might be running into an AMSI issue. Can you try to disable Defender and see if the issue persists?

You just need to set the following by using gpedit:

Local Computer Policy -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Defender Antivirus -> Turn off Windows Defender Antivirus: Enabled
Local Computer Policy -> Computer Configuration -> Administrative Templates -> Windows Components -> Windows Defender Antivirus -> Real-time Protection -> Turn off real-time protection: Enabled

**Comment by cobbr** [comment] 2019-08-22 05:06
@avi8892 Did you disable to exact group policies I listed above? Just turning off Windows Defender will *not* work.

**Comment by avi8892** [comment] 2019-08-27 15:22
I will update on the next 2 days. Need to check it won window 7.

**Comment by avi8892** [comment] 2019-08-28 08:24
Bypassuac Tested on Windows server 2008 and getting the same error. It is nothing about AMSI.

**Comment by avi8892** [comment] 2019-08-28 20:16
Windows defender isn't installed on windows server 2008

**Comment by pn0pz** [comment] 2019-08-30 16:03
hi I came across this today and comparing the BypassUACGrunt params in the web UI with the .NET code in the task there seems to be a mismatch. In the UI it specifies a "Launcher" param only while the Task code is:

`public static string Execute(string Command, string Parameters, string Directory = "C:\\WINDOWS\\System32\\", string ProcessID = "0")`

So that might explain the 'Parameter count mismatch' error. 

If running BypassUACCommand don't forget to add the '\\' to the end of the Path parameter. I have yet to get BypassUACCommand to run a powershell grunt manually due to some kind of limitation in CreateProcessWithLogonW() arguments within Sharpsploit (but that is another issue).

**Comment by cobbr** [comment] 2019-08-30 16:32
@pn0pz There's some backend magic that converts the "Launcher" param into the parameters needed, so I don't think this is the issue.

@avi8892 Are you only using the PowerShell launcher with BypassUACGrunt? Did you configure the PowerShell Launcher and click Generate before running BypassUACGrunt?

**Comment by avi8892** [comment] 2019-08-30 16:36
Sure.
1. Generated PowerShell payload.
2. Had a connection back from compromised host with local administrator rights.
3. Tried to use BybassUACGrunt to elevate my privileges from low integrity to high.
מאת: Ryan Cobb<mailto:notifications@github.com>
נשלח: יום שישי 30 אוגוסט 2019 19:32
אל: cobbr/Covenant<mailto:Covenant@noreply.github.com>
עותק: AviOz7<mailto:avi8892@hotmail.com>; Mention<mailto:mention@noreply.github.com>
נושא: Re: [cobbr/Covenant] Can not run Tasks (Any) - Getting an errors (#38)


@pn0pz<https://github.com/pn0pz> There's some backend magic that converts the "Launcher" param into the parameters needed, so I don't think this is the issue.

@avi8892<https://github.com/avi8892> Are you only using the PowerShell launcher with BypassUACGrunt? Did you configure the PowerShell Launcher and click Generate before running BypassUACGrunt?

**Comment by pn0pz** [comment] 2019-08-30 16:52
@cobbr OK, I forgot to mention I am running Covenant on Linux too (Parrot OS & non-docker).

**Comment by cobbr** [comment] 2019-08-30 16:54
@pn0pz Are you getting the same issue as @avi8892? I just re-tested and I can't reproduce the issue.

**Comment by pn0pz** [comment] 2019-08-30 17:15
yes just reinstalled and had the same issue from scratch. 

![image](https://user-images.githubusercontent.com/54716930/64039144-e0740480-cb51-11e9-8aed-46c57bb33509.png)

**Comment by cobbr** [comment] 2019-09-01 16:07
@pn0pz Ahhhh okay. That's not how BypassUACGrunt is intended to be used. It should be just `BypassUACGrunt powershell`. The module will grab the launcher string from the launcher by itself.

Alternatively you can use `BypassUACCommand` with a long command-line like that.

**Comment by pn0pz** [comment] 2019-09-07 09:01
> @pn0pz Ahhhh okay. That's not how BypassUACGrunt is intended to be used. It should be just `BypassUACGrunt powershell`. The module will grab the launcher string from the launcher by itself.
> 
> Alternatively you can use `BypassUACCommand` with a long command-line like that.

I tried with just the default and I still get the Parameter count mismatch error :(

![image](https://user-images.githubusercontent.com/54716930/64472443-67c70680-d156-11e9-8205-f70c30b0b8bc.png)

**Comment by pn0pz** [comment] 2019-09-07 10:52
> @pn0pz There's some backend magic that converts the "Launcher" param into the parameters needed, so I don't think this is the issue.

I have logged the params received by the Grunt in TaskExecute and the array just contains the "Powershell" string so the backend magic doesn't seem to be applying in this instance.

**Comment by Agent-Tiro** [comment] 2019-09-16 22:33
I am having these same issues as well. If I use the interact and run the command I get a message that it failed to execute with high integrity. If I use the task gui I get the param mismatch error. It doesn't matter if I use the Grunt or Command tasks. Both perform the same.

**Comment by cobbr** [comment] 2019-09-17 03:45
@Agent-Tiro The "failed to execute with high integrity" means the Task completed "successfully", but the technique was not successful.

The param mismatch error message is strange, and could be a Covenant bug. What OS are you running Covenant on?

**Comment by Agent-Tiro** [comment] 2019-09-17 06:36
@cobbr I'm running this on up to date kali, running against up to date Win10 enterprise. 

So it sounds like the failed to execute is the correct error since my lab machine is patched against this method. But using the gui task to perform the exact same command I get the param mis-match.

**Comment by stlorenz** [comment] 2019-09-18 10:01
I can confirm this behaviour. 
When run via GUI th eexecuted command is 
``
BypassUACCommand /command:"powershell"
``
Which leads to parameter count error. 

Running ``
BypassUAC powershell
`` in interactive mode fails to gain high integrity on a fresh Windows 1903

**Comment by cobbr** [comment] 2019-09-23 23:27
I believe I have fixed this in 886d6a04a5b6bb2ab96c50b35a603cc95971252c

Had to fix some cli parsing and there was some inconsistencies between using the Task tab or Interact tab.

To be clear, if you get the output "failed to execute with high integrity", Covenant has executed the task successfully. The technique may or may not succeed on your particular system. If you get a "parameter count error", this is an issue with Covenant, which I believe I have fixed.

Could you all re-pull and re-test and let me know if it works for you now? @stlorenz @Agent-Tiro @pn0pz @avi8892

**Comment by cobbr** [comment] 2019-09-25 13:19
Closing for now, let me know if this issue persists and we can re-open.

**Closed by cobbr** 2019-09-25 13:19 UTC
Labels: bug
